({
/* General resources */
search: "Search",
filter: "Filter",
"new": "New",

/* actions */
undo: "Undo",
redo: "Redo",
copy: "Copy",
paste: "Paste",
cut: "Cut",
"delete": "Delete",
surround: "Surround",
properties: "Properties",
styles: "Styles",
events: "Events",
preferences: "Preferences",

addPane: "Add Pane",
addColumn: "Add Column",
addRow: "Add Row",
removeColumn: "Remove Column",
removeRow: "Remove Row",
joinColumn: "Join Column",
joinRow: "Join Row",
splitColumn: "Split Column",
splitRow: "Split Row",
alignLeft: "Align Left",
alignRight: "Align Right",
alignTop: "Align Top",
alignBottom: "Align Bottom",
show: "Show",
hide: "Hide",
addMenuItem: "Add Menu Item",
addSubMenu: "Add Sub Menu",
addMenuBarItem: "Add MenuBar Item",
addPopupMenuBar: "Add Popup MenuBarItem",

/* dialogs */
ok: "OK",
cancel: "Cancel",

/* PropertyPane */
page: "Page",
title: "Title",
metaInfo: "Meta Info",
httpEquiv: "HTTP Equiv",
style: "Style",
theme: "Theme",
styleSheets: "Style Sheets",
rules: "Rules",
url: "URL",
externalScripts: "External Scripts",
modules: "Modules",
name: "Name",
value: "Value",
add: "Add",
remove: "Remove",

staticOptions: "Static Options",
axisOptions: "Axis Options",
series: "Series",
axis: "Axis",
option: "Option",
selected: "Selected",
staticItems: "Static Items",
dataStore: "Data Store",
query: "Query",
fields: "Fields",
field: "Field",
label: "Label",
width: "Width",
edit: "Edit",
key: "Key",
rootId: "Root ID",
rootLabel: "Root Label",
childrenAttrs: "Children Attributes",
items: "Items",
type: "Type",
widget: "Widget",

/* StylePane */
position: "Position",
size: "Size",
layout: "Layout",
visual: "Visual",
text: "Text",
border: "Border",
table: "Table",
list: "List",
aural: "Aural",
others: "Others",

/* EventPane */
onLoad: "Load",
onUnload: "Unload",
script: "Script",
methodCall: "Method Call",
serviceCall: "Service Call",
object: "Object",
method: "Method",
parameters: "Parameters",
result: "Result",
service: "Service",
type: "Type",
content: "Content",
source: "Source",
target: "Target",
property: "Property",

/* PreferencePane */
flowLayout: "Flow Layout",
snapToNearestWidget: "Snap to nearest widget",
warnOnCSSOverride: "Warn on CSS Override",
liveEdit: "Live Edit",

/* WidgetSelectionPane*/
selectorPrefix: "Selector Prefix",
component: "Component",

__dummy__: ""
})
