define(
//begin v1.x content
{
	"dateFormat-medium": "dd/MM/y G",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-yyMMM": "MMM-y G",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyQQQQ": "QQQQ 'de' y G",
	"dateFormatItem-EEEd": "EEE d",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "EEE, d MMM y G",
	"dateFormatItem-yyyyMEd": "EEE d/M/y G",
	"dateFormatItem-yyyyMMMM": "MMMM 'de' y G",
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"dateFormatItem-MMd": "d/MM",
	"dateFormatItem-yyyyMM": "MM/y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-MMMdd": "dd-MMM",
	"dateFormatItem-yyMM": "MM/y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyQ": "Q y G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormat-short": "dd/MM/y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "hh a",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "EEEE d 'de' MMMM 'de' y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyyyQ": "Q y G"
}
//end v1.x content
);