({
	"clearFilterDialogTitle": "Clear Filter",
	"filterDefDialogTitle": "Filter",
	"ruleTitleTemplate": "Rule ${0}",
	
	"conditionEqual": "equal",
	"conditionNotEqual": "does not equal",
	"conditionLess": "is less than",
	"conditionLessEqual": "less than or equal",
	"conditionLarger": "is greater than",
	"conditionLargerEqual": "greater than or equal",
	"conditionContains": "contains",
	"conditionIs": "is",
	"conditionStartsWith": "starts with",
	"conditionEndWith": "ends with",
	"conditionNotContain": "does not contain",
	"conditionIsNot": "is not",
	"conditionNotStartWith": "does not start with",
	"conditionNotEndWith": "does not end with",
	"conditionBefore": "before",
	"conditionAfter": "after",
	"conditionRange": "range",
	"conditionIsEmpty": "is empty",
	
	"all": "all",
	"any": "any",
	"relationAll": "all rules",
	"waiRelAll": "Match all of the following rules:",
	"relationAny": "any rules",
	"waiRelAny": "Match any of the following rules:",
	"relationMsgFront": "Match",
	"relationMsgTail": "",
	"and": "and",
	"or": "or",
	
	"addRuleButton": "Add Rule",
	"waiAddRuleButton": "Add a new rule",
	"removeRuleButton": "Remove Rule",
	"waiRemoveRuleButtonTemplate": "Remove rule ${0}",
	
	"cancelButton": "Cancel",
	"waiCancelButton": "Cancel this dialog",
	"clearButton": "Clear",
	"waiClearButton": "Clear the filter",
	"filterButton": "Filter",
	"waiFilterButton": "Submit the filter",
	
	"columnSelectLabel": "Column",
	"waiColumnSelectTemplate": "Column for rule ${0}",
	"conditionSelectLabel": "Condition",
	"waiConditionSelectTemplate": "Condition for rule ${0}",
	"valueBoxLabel": "Value",
	"waiValueBoxTemplate": "Enter value to filter for rule ${0}",
	
	"rangeTo": "to",
	"rangeTemplate": "from ${0} to ${1}",
	
	"statusTipHeaderColumn": "Column",
	"statusTipHeaderCondition": "Rules",
	"statusTipTitle": "Filter Bar",
	"statusTipMsg": "Click the filter bar here to filter on values in ${0}.",
	"anycolumn": "any column",
	"statusTipTitleNoFilter": "Filter Bar",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Match",
	"statusTipRelPost": "rules.",
	
	"defaultItemsName": "items",
	"filterBarMsgHasFilterTemplate": "${0} of ${1} ${2} shown.",
	"filterBarMsgNoFilterTemplate": "No filter applied",
	
	"filterBarDefButton": "Define filter",
	"waiFilterBarDefButton": "Filter the table",
	"a11yFilterBarDefButton": "Filter...",
	"filterBarClearButton": "Clear filter",
	"waiFilterBarClearButton": "Clear the filter",
	"closeFilterBarBtn": "Close filter bar",
	
	"clearFilterMsg": "This will remove the filter and show all available records.",
	"anyColumnOption": "Any Column",
	
	"trueLabel": "True",
	"falseLabel": "False"
})

