define({ root:

//begin v1.x content
{
	"days-format-narrow@localeAlias290": {
		"bundle": "gregorian",
		"target": "days-standAlone-narrow"
	},
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"timeFormat@localeAlias308": {
		"bundle": "gregorian",
		"target": "timeFormat"
	},
	"dateFormatItem-MMMEd": "E MMM d",
	"quarters-standAlone-abbr@localeAlias297": {
		"bundle": "gregorian",
		"target": "quarters-format-abbr"
	},
	"eraNarrow": [
		"M",
		"T",
		"S",
		"H"
	],
	"quarters-standAlone-abbr@localeAlias298": {
		"bundle": "gregorian",
		"target": "quarters-format-wide"
	},
	"dayPeriods-format-narrow@localeAlias302": {
		"bundle": "gregorian",
		"target": "dayPeriods-format-abbr"
	},
	"quarters-format-abbr@localeAlias295": {
		"bundle": "gregorian",
		"target": "quarters-format-wide"
	},
	"quarters-format-narrow@localeAlias296": {
		"bundle": "gregorian",
		"target": "quarters-standAlone-narrow"
	},
	"dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}",
	"dayPeriods-format-narrow@localeAlias303": {
		"bundle": "gregorian",
		"target": "dayPeriods-format-wide"
	},
	"dayPeriods-format-narrow@localeAlias305": {
		"bundle": "gregorian",
		"target": "dayPeriods-format-abbr"
	},
	"dayPeriods-format-narrow@localeAlias306": {
		"bundle": "gregorian",
		"target": "dayPeriods-format-wide"
	},
	"dateFormat-long": "G y MMMM d",
	"months-format-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"months-standAlone-wide@localeAlias287": {
		"bundle": "gregorian",
		"target": "months-format-wide"
	},
	"dayPeriods-format-wide-pm": "PM",
	"dateFormat-full": "EEEE, G y MMMM dd",
	"dateFormatItem-Md": "M-d",
	"dayPeriods-format-abbr-am": "AM",
	"dateTimeFormats-appendItem-Second": "{0} ({2}: {1})",
	"months-standAlone-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"timeFormat-long": "HH:mm:ss z",
	"dateTimeFormats-appendItem-Era": "{0} {1}",
	"months-format-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dayPeriods@localeAlias300": {
		"bundle": "gregorian",
		"target": "dayPeriods"
	},
	"timeFormat-full": "HH:mm:ss zzzz",
	"dateTimeFormats-appendItem-Week": "{0} ({2}: {1})",
	"dateFormatItem-H": "HH",
	"months-standAlone-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"months-standAlone-abbr@localeAlias285": {
		"bundle": "gregorian",
		"target": "months-format-abbr"
	},
	"months-standAlone-abbr@localeAlias286": {
		"bundle": "gregorian",
		"target": "months-format-wide"
	},
	"months-format-abbr@localeAlias283": {
		"bundle": "gregorian",
		"target": "months-format-wide"
	},
	"days-standAlone-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"dateFormatItem-yyyyMMM": "GGGGG yy MMM",
	"dateFormatItem-yyyyMMMd": "GGGGG yy MMM d",
	"dateFormatItem-MMMMd": "MMMM d",
	"quarters@localeAlias294": {
		"bundle": "gregorian",
		"target": "quarters"
	},
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"eraAbbr": [
		"Taika",
		"Hakuchi",
		"Hakuhō",
		"Shuchō",
		"Taihō",
		"Keiun",
		"Wadō",
		"Reiki",
		"Yōrō",
		"Jinki",
		"Tempyō",
		"Tempyō-kampō",
		"Tempyō-shōhō",
		"Tempyō-hōji",
		"Temphō-jingo",
		"Jingo-keiun",
		"Hōki",
		"Ten-ō",
		"Enryaku",
		"Daidō",
		"Kōnin",
		"Tenchō",
		"Shōwa",
		"Kajō",
		"Ninju",
		"Saiko",
		"Tennan",
		"Jōgan",
		"Genkei",
		"Ninna",
		"Kampyō",
		"Shōtai",
		"Engi",
		"Enchō",
		"Shōhei",
		"Tengyō",
		"Tenryaku",
		"Tentoku",
		"Ōwa",
		"Kōhō",
		"Anna",
		"Tenroku",
		"Ten-en",
		"Jōgen",
		"Tengen",
		"Eikan",
		"Kanna",
		"Ei-en",
		"Eiso",
		"Shōryaku",
		"Chōtoku",
		"Chōhō",
		"Kankō",
		"Chōwa",
		"Kannin",
		"Jian",
		"Manju",
		"Chōgen",
		"Chōryaku",
		"Chōkyū",
		"Kantoku",
		"Eishō",
		"Tengi",
		"Kōhei",
		"Jiryaku",
		"Enkyū",
		"Shōho",
		"Shōryaku",
		"Eiho",
		"Ōtoku",
		"Kanji",
		"Kaho",
		"Eichō",
		"Shōtoku",
		"Kōwa",
		"Chōji",
		"Kashō",
		"Tennin",
		"Ten-ei",
		"Eikyū",
		"Gen-ei",
		"Hoan",
		"Tenji",
		"Daiji",
		"Tenshō",
		"Chōshō",
		"Hoen",
		"Eiji",
		"Kōji",
		"Tenyō",
		"Kyūan",
		"Ninpei",
		"Kyūju",
		"Hogen",
		"Heiji",
		"Eiryaku",
		"Ōho",
		"Chōkan",
		"Eiman",
		"Nin-an",
		"Kaō",
		"Shōan",
		"Angen",
		"Jishō",
		"Yōwa",
		"Juei",
		"Genryuku",
		"Bunji",
		"Kenkyū",
		"Shōji",
		"Kennin",
		"Genkyū",
		"Ken-ei",
		"Shōgen",
		"Kenryaku",
		"Kenpō",
		"Shōkyū",
		"Jōō",
		"Gennin",
		"Karoku",
		"Antei",
		"Kanki",
		"Jōei",
		"Tempuku",
		"Bunryaku",
		"Katei",
		"Ryakunin",
		"En-ō",
		"Ninji",
		"Kangen",
		"Hōji",
		"Kenchō",
		"Kōgen",
		"Shōka",
		"Shōgen",
		"Bun-ō",
		"Kōchō",
		"Bun-ei",
		"Kenji",
		"Kōan",
		"Shōō",
		"Einin",
		"Shōan",
		"Kengen",
		"Kagen",
		"Tokuji",
		"Enkei",
		"Ōchō",
		"Shōwa",
		"Bunpō",
		"Genō",
		"Genkyō",
		"Shōchū",
		"Kareki",
		"Gentoku",
		"Genkō",
		"Kemmu",
		"Engen",
		"Kōkoku",
		"Shōhei",
		"Kentoku",
		"Bunchũ",
		"Tenju",
		"Kōryaku",
		"Kōwa",
		"Genchũ",
		"Meitoku",
		"Kakei",
		"Kōō",
		"Meitoku",
		"Ōei",
		"Shōchō",
		"Eikyō",
		"Kakitsu",
		"Bun-an",
		"Hōtoku",
		"Kyōtoku",
		"Kōshō",
		"Chōroku",
		"Kanshō",
		"Bunshō",
		"Ōnin",
		"Bunmei",
		"Chōkyō",
		"Entoku",
		"Meiō",
		"Bunki",
		"Eishō",
		"Taiei",
		"Kyōroku",
		"Tenmon",
		"Kōji",
		"Eiroku",
		"Genki",
		"Tenshō",
		"Bunroku",
		"Keichō",
		"Genwa",
		"Kan-ei",
		"Shōho",
		"Keian",
		"Shōō",
		"Meiryaku",
		"Manji",
		"Kanbun",
		"Enpō",
		"Tenwa",
		"Jōkyō",
		"Genroku",
		"Hōei",
		"Shōtoku",
		"Kyōhō",
		"Genbun",
		"Kanpō",
		"Enkyō",
		"Kan-en",
		"Hōryaku",
		"Meiwa",
		"An-ei",
		"Tenmei",
		"Kansei",
		"Kyōwa",
		"Bunka",
		"Bunsei",
		"Tenpō",
		"Kōka",
		"Kaei",
		"Ansei",
		"Man-en",
		"Bunkyū",
		"Genji",
		"Keiō",
		"Meiji",
		"Taishō",
		"Shōwa",
		"Heisei"
	],
	"days-standAlone-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"dateFormatItem-h": "hh a",
	"dateTimeFormat-long": "{1} {0}",
	"dayPeriods-format-narrow-am": "AM",
	"months-format-narrow@localeAlias284": {
		"bundle": "gregorian",
		"target": "months-standAlone-narrow"
	},
	"dateTimeFormat-full": "{1} {0}",
	"days-format-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateTimeFormats-appendItem-Day": "{0} ({2}: {1})",
	"dateFormatItem-hm": "hh:mm a",
	"dateTimeFormats-appendItem-Year": "{0} {1}",
	"dayPeriods-format-abbr@localeAlias301": {
		"bundle": "gregorian",
		"target": "dayPeriods-format-wide"
	},
	"dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr@localeAlias304": {
		"bundle": "gregorian",
		"target": "dayPeriods-format-wide"
	},
	"days-standAlone-wide@localeAlias293": {
		"bundle": "gregorian",
		"target": "days-format-wide"
	},
	"days-format-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"eraNames": [
		"Taika",
		"Hakuchi",
		"Hakuhō",
		"Shuchō",
		"Taihō",
		"Keiun",
		"Wadō",
		"Reiki",
		"Yōrō",
		"Jinki",
		"Tempyō",
		"Tempyō-kampō",
		"Tempyō-shōhō",
		"Tempyō-hōji",
		"Temphō-jingo",
		"Jingo-keiun",
		"Hōki",
		"Ten-ō",
		"Enryaku",
		"Daidō",
		"Kōnin",
		"Tenchō",
		"Shōwa",
		"Kajō",
		"Ninju",
		"Saiko",
		"Tennan",
		"Jōgan",
		"Genkei",
		"Ninna",
		"Kampyō",
		"Shōtai",
		"Engi",
		"Enchō",
		"Shōhei",
		"Tengyō",
		"Tenryaku",
		"Tentoku",
		"Ōwa",
		"Kōhō",
		"Anna",
		"Tenroku",
		"Ten-en",
		"Jōgen",
		"Tengen",
		"Eikan",
		"Kanna",
		"Ei-en",
		"Eiso",
		"Shōryaku",
		"Chōtoku",
		"Chōhō",
		"Kankō",
		"Chōwa",
		"Kannin",
		"Jian",
		"Manju",
		"Chōgen",
		"Chōryaku",
		"Chōkyū",
		"Kantoku",
		"Eishō",
		"Tengi",
		"Kōhei",
		"Jiryaku",
		"Enkyū",
		"Shōho",
		"Shōryaku",
		"Eiho",
		"Ōtoku",
		"Kanji",
		"Kaho",
		"Eichō",
		"Shōtoku",
		"Kōwa",
		"Chōji",
		"Kashō",
		"Tennin",
		"Ten-ei",
		"Eikyū",
		"Gen-ei",
		"Hoan",
		"Tenji",
		"Daiji",
		"Tenshō",
		"Chōshō",
		"Hoen",
		"Eiji",
		"Kōji",
		"Tenyō",
		"Kyūan",
		"Ninpei",
		"Kyūju",
		"Hogen",
		"Heiji",
		"Eiryaku",
		"Ōho",
		"Chōkan",
		"Eiman",
		"Nin-an",
		"Kaō",
		"Shōan",
		"Angen",
		"Jishō",
		"Yōwa",
		"Juei",
		"Genryuku",
		"Bunji",
		"Kenkyū",
		"Shōji",
		"Kennin",
		"Genkyū",
		"Ken-ei",
		"Shōgen",
		"Kenryaku",
		"Kenpō",
		"Shōkyū",
		"Jōō",
		"Gennin",
		"Karoku",
		"Antei",
		"Kanki",
		"Jōei",
		"Tempuku",
		"Bunryaku",
		"Katei",
		"Ryakunin",
		"En-ō",
		"Ninji",
		"Kangen",
		"Hōji",
		"Kenchō",
		"Kōgen",
		"Shōka",
		"Shōgen",
		"Bun-ō",
		"Kōchō",
		"Bun-ei",
		"Kenji",
		"Kōan",
		"Shōō",
		"Einin",
		"Shōan",
		"Kengen",
		"Kagen",
		"Tokuji",
		"Enkei",
		"Ōchō",
		"Shōwa",
		"Bunpō",
		"Genō",
		"Genkyō",
		"Shōchū",
		"Kareki",
		"Gentoku",
		"Genkō",
		"Kemmu",
		"Engen",
		"Kōkoku",
		"Shōhei",
		"Kentoku",
		"Bunchũ",
		"Tenju",
		"Kōryaku",
		"Kōwa",
		"Genchũ",
		"Meitoku",
		"Kakei",
		"Kōō",
		"Meitoku",
		"Ōei",
		"Shōchō",
		"Eikyō",
		"Kakitsu",
		"Bun-an",
		"Hōtoku",
		"Kyōtoku",
		"Kōshō",
		"Chōroku",
		"Kanshō",
		"Bunshō",
		"Ōnin",
		"Bunmei",
		"Chōkyō",
		"Entoku",
		"Meiō",
		"Bunki",
		"Eishō",
		"Taiei",
		"Kyōroku",
		"Tenmon",
		"Kōji",
		"Eiroku",
		"Genki",
		"Tenshō",
		"Bunroku",
		"Keichō",
		"Genwa",
		"Kan-ei",
		"Shōho",
		"Keian",
		"Shōō",
		"Meiryaku",
		"Manji",
		"Kanbun",
		"Enpō",
		"Tenwa",
		"Jōkyō",
		"Genroku",
		"Hōei",
		"Shōtoku",
		"Kyōhō",
		"Genbun",
		"Kanpō",
		"Enkyō",
		"Kan-en",
		"Hōryaku",
		"Meiwa",
		"An-ei",
		"Tenmei",
		"Kansei",
		"Kyōwa",
		"Bunka",
		"Bunsei",
		"Tenpō",
		"Kōka",
		"Kaei",
		"Ansei",
		"Man-en",
		"Bunkyū",
		"Genji",
		"Keiō",
		"Meiji",
		"Taishō",
		"Shōwa",
		"Heisei"
	],
	"days-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"dateFormatItem-yyyyMd": "GGGGG yy-MM-dd",
	"days-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})",
	"dayPeriods-format-wide-am": "AM",
	"dateTimeFormats-appendItem-Month": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})",
	"quarters-standAlone-wide@localeAlias299": {
		"bundle": "gregorian",
		"target": "quarters-format-wide"
	},
	"days-standAlone-abbr@localeAlias291": {
		"bundle": "gregorian",
		"target": "days-format-abbr"
	},
	"days-standAlone-abbr@localeAlias292": {
		"bundle": "gregorian",
		"target": "days-format-wide"
	},
	"dateFormat-short": "G yy-MM-dd",
	"days-format-abbr@localeAlias289": {
		"bundle": "gregorian",
		"target": "days-format-wide"
	},
	"dateFormatItem-Ed": "E d",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"dateFormat-medium": "G y MMM d",
	"days@localeAlias288": {
		"bundle": "gregorian",
		"target": "days"
	},
	"dateFormatItem-yyyyM": "GGGGG yy-MM",
	"dayPeriods-format-narrow-pm": "PM",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-yyyyQ": "GGGGG yy Q",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "hh:mm:ss a",
	"eraNames@localeAlias307": {
		"bundle": "japanese",
		"target": "eraAbbr"
	},
	"dateFormatItem-yyyy": "yy GGG",
	"months@localeAlias282": {
		"bundle": "gregorian",
		"target": "months"
	}
}
//end v1.x content
,
	"ar": true,
	"da": true,
	"de": true,
	"el": true,
	"en": true,
	"en-gb": true,
	"es": true,
	"fi": true,
	"fr": true,
	"he": true,
	"it": true,
	"ja": true,
	"ko": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-pt": true,
	"ru": true,
	"sv": true,
	"th": true,
	"tr": true,
	"zh": true,
	"zh-hant": true
});