define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y G",
	"dateFormatItem-yQ": "Q y G",
	"dateFormatItem-MMMEd": "dd MMM E",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y G",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"O",
		"≈û",
		"M",
		"N",
		"M",
		"H",
		"T",
		"A",
		"E",
		"E",
		"K",
		"A"
	],
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y G",
	"days-standAlone-narrow": [
		"P",
		"P",
		"S",
		"√á",
		"P",
		"C",
		"C"
	],
	"dateFormat-long": "dd MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-yyMM": "MM/yy G",
	"dateFormat-medium": "dd MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM yy G",
	"dateFormatItem-yyQQQQ": "QQQQ yy G",
	"dateFormatItem-yMMMM": "MMMM y G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-yyQ": "Q yy G",
	"months-format-abbr": [
		"Oca",
		"≈ûub",
		"Mar",
		"Nis",
		"May",
		"Haz",
		"Tem",
		"Aƒüu",
		"Eyl",
		"Eki",
		"Kas",
		"Ara"
	],
	"dateFormatItem-H": "HH",
	"quarters-format-abbr": [
		"√á1",
		"√á2",
		"√á3",
		"√á4"
	],
	"days-format-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"√áar",
		"Per",
		"Cum",
		"Cmt"
	],
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "dd MMM y G",
	"dateFormatItem-MEd": "dd/MM E",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yyyy G",
	"dateFormatItem-yMMMEd": "dd MMM y G EEE",
	"dateFormat-full": "dd MMMM y G EEEE",
	"dateFormatItem-Md": "dd/MM",
	"dateFormatItem-yMEd": "dd.MM.y G EEE",
	"months-format-wide": [
		"Ocak",
		"≈ûubat",
		"Mart",
		"Nisan",
		"Mayƒ±s",
		"Haziran",
		"Temmuz",
		"Aƒüustos",
		"Eyl√ºl",
		"Ekim",
		"Kasƒ±m",
		"Aralƒ±k"
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1. √ßeyrek",
		"2. √ßeyrek",
		"3. √ßeyrek",
		"4. √ßeyrek"
	],
	"days-format-wide": [
		"Pazar",
		"Pazartesi",
		"Salƒ±",
		"√áar≈üamba",
		"Per≈üembe",
		"Cuma",
		"Cumartesi"
	]
}
//end v1.x content
);