define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/yyyy",
	"dateFormatItem-yyyyMMMEd": "dd MMM y G EEE",
	"dateFormatItem-yQ": "Q yyyy",
	"dateFormatItem-MMMEd": "dd MMM E",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"Muharrem",
		"Safer",
		"Rebi√ºlevvel",
		"Rebi√ºlahir",
		"Cemaziyelevvel",
		"Cemaziyelahir",
		"Recep",
		"≈ûaban",
		"Ramazan",
		"≈ûevval",
		"Zilkade",
		"Zilhicce"
	],
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"days-standAlone-narrow": [
		"P",
		"P",
		"S",
		"√á",
		"P",
		"C",
		"C"
	],
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormat-long": "dd MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-yyMM": "MM/yy G",
	"dateFormat-medium": "dd MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM yy G",
	"dateFormatItem-yyQQQQ": "QQQQ yy G",
	"dateFormatItem-ms": "mm:ss",
	"months-standAlone-wide": [
		"Muharrem",
		"Safer",
		"Rebi√ºlevvel",
		"Rebi√ºlahir",
		"Cemaziyelevvel",
		"Cemaziyelahir",
		"Recep",
		"≈ûaban",
		"Ramazan",
		"≈ûevval",
		"Zilkade",
		"Zilhicce"
	],
	"dateFormatItem-yyyyMMMd": "dd MMM y G",
	"dateFormatItem-yyyyMEd": "dd.MM.y G EEE",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-yyQ": "Q yy G",
	"months-format-abbr": [
		"Muharrem",
		"Safer",
		"Rebi√ºlevvel",
		"Rebi√ºlahir",
		"Cemaziyelevvel",
		"Cemaziyelahir",
		"Recep",
		"≈ûaban",
		"Ramazan",
		"≈ûevval",
		"Zilkade",
		"Zilhicce"
	],
	"dateFormatItem-H": "HH",
	"quarters-format-abbr": [
		"√á1",
		"√á2",
		"√á3",
		"√á4"
	],
	"days-format-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"√áar",
		"Per",
		"Cum",
		"Cmt"
	],
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "dd/MM E",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yyyy G",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormatItem-yMMMEd": "dd MMM y EEE",
	"dateFormat-full": "dd MMMM y G EEEE",
	"dateFormatItem-Md": "dd/MM",
	"dateFormatItem-yyyyQ": "Q y G",
	"dateFormatItem-yMEd": "dd.MM.yyyy EEE",
	"months-format-wide": [
		"Muharrem",
		"Safer",
		"Rebiülevvel",
		"Rebiülahir",
		"Cemaziyelevvel",
		"Cemaziyelahir",
		"Recep",
		"Şaban",
		"Ramazan",
		"Şevval",
		"Zilkade",
		"Zilhicce"
	],
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1. √ßeyrek",
		"2. √ßeyrek",
		"3. √ßeyrek",
		"4. √ßeyrek"
	],
	"days-format-wide": [
		"Pazar",
		"Pazartesi",
		"Salƒ±",
		"√áar≈üamba",
		"Per≈üembe",
		"Cuma",
		"Cumartesi"
	]
}
//end v1.x content
);