({
	'bold': 'Aldine',
	'copy': 'Copiere',
	'cut': 'Tăiere',
	'delete': 'Ştergere',
	'indent': 'Indentare',
	'insertHorizontalRule': 'Regulă orizontală',
	'insertOrderedList': 'Listă numerotată',
	'insertUnorderedList': 'Listă cu marcaje',
	'italic': 'Cursive',
	'justifyCenter': 'Aliniere pe centru',
	'justifyFull': 'Aliniere',
	'justifyLeft': 'Aliniere la stânga',
	'justifyRight': 'Aliniere la dreapta',
	'outdent': 'Outdentare',
	'paste': 'Lipire',
	'redo': 'Repetare acţiune',
	'removeFormat': 'Înlăturare format',
	'selectAll': 'Selectare toate',
	'strikethrough': 'Suprascriere linie',
	'subscript': 'Scriere indice inferior',
	'superscript': 'Scriere indice superior',
	'underline': 'Subliniere',
	'undo': 'Anulare acţiune',
	'unlink': 'Înlăturare legătură',
	'createLink': 'Creare legătură',
	'toggleDir': 'Comutare direcţie',
	'insertImage': 'Inserare imagine',
	'insertTable': 'Inserare/Editare tabelă',
	'toggleTableBorder': 'Comutare bordură tabelă',
	'deleteTable': 'Ştergere tabelă',
	'tableProp': 'Proprietăţi tabelă',
	'htmlToggle': 'Sursă HTML',
	'foreColor': 'Culoare prim plan',
	'hiliteColor': 'Culoare fundal',
	'plainFormatBlock': 'Stil paragraf',
	'formatBlock': 'Stil paragraf',
	'fontSize': 'Dimensiune font',
	'fontName': 'Nume font',
	'tabIndent': 'Indentare cu tab',
	"fullScreen": "Comutare ecran complet",
	"viewSource": "Vizualizare sursă HTML",
	"print": "Tipărire",
	"newPage": "Pagină nouă",
	/* Error messages */
	'systemShortcut': 'Acţiunea "${0}" este disponibilă în browser folosind o scurtătură de la tastatură. Folosiţi ${1}.'
})

