package org.davinci.server.user;

public interface IPerson {
    public String getEmail();
    
    /* name for display purposes only */
    public String getDisplayName();
    
    /* user ID may be autogenerated or some other unique key */
    public String getUserID();
}
