define({
	colors:[
	        "firebrick",
	        "darkblue",
	        "darkgreen",
	        "purple",
	        "darkorange",
	        "darkgoldenrod",
	        "brown",
	        "darkgrey",
	        "darkcyan",
	        "deeppink"
	        ]
});
