({
	smiley: "Insert Emoticon",
	emoticonSmile: "smile",
	emoticonLaughing: "laughing",
	emoticonWink: "wink",
	emoticonGrin: "grin",
	emoticonCool: "cool",
	emoticonAngry: "angry",
	emoticonHalf: "half",
	emoticonEyebrow: "eyebrow",
	emoticonFrown: "frown",
	emoticonShy: "shy",
	emoticonGoofy: "goofy",
	emoticonOops: "oops",
	emoticonTongue: "tongue",
	emoticonIdea: "idea",
	emoticonYes: "yes",
	emoticonNo: "no",
	emoticonAngel: "angel",
	emoticonCrying: "crying"
})
