define(
{
/* General resources */
search: "検索",
filter: "フィルター",
"new": "新規",

/* actions */
undo: "元に戻す",
redo: "やり直す",
copy: "コピー",
paste: "貼り付け",
cut: "切り取り",
"delete": "削除",
properties: "プロパティ",
styles: "スタイル",
events: "イベント",
preferences: "プリファレンス",

addPane: "ペインの追加",
addColumn: "列の追加",
addRow: "行の追加",
removeColumn: "列の削除",
removeRow: "行の追加",
joinColumn: "列の結合",
joinRow: "行の結合",
splitColumn: "列の分割",
splitRow: "行の分割",
alignLeft: "左揃え",
alignRight: "右揃え",
alignTop: "上揃え",
alignBottom: "下揃え",
show: "表示",
hide: "非表示",
addMenuItem: "メニューアイテムの追加",
addSubMenu: "サブメニューの追加",

/* dialogs */
ok: "OK",
cancel: "キャンセル",

/* PropertyPane */
page: "ページ",
title: "タイトル",
metaInfo: "メタ情報",
httpEquiv: "HTTPヘッダ",
style: "スタイル",
theme: "テーマ",
styleSheets: "スタイルシート",
rules: "ルール",
url: "URL",
externalScripts: "外部スクリプト",
modules: "モジュール",
name: "名前",
value: "値",
add: "追加",
remove: "削除",

staticOptions: "固定選択項目",
option: "選択項目",
selected: "選択",
staticItems: "固定項目",
dataStore: "データストア",
query: "クエリ",
fields: "フィールド",
field: "フィールド",
label: "ラベル",
width: "幅",
edit: "編集",
key: "キー",
rootId: "ルートID",
rootLabel: "ルートラベル",
childrenAttrs: "子ノード属性",

/* StylePane */
position: "位置",
size: "サイズ",
layout: "レイアウト",
visual: "ビジュアル",
text: "テキスト",
border: "枠",
table: "表",
list: "リスト",
aural: "音声",
others: "その他",

/* EventPane */
onLoad: "ロード",
onUnload: "アンロード",
script: "スクリプト",
methodCall: "メソッド呼出",
serviceCall: "サービス呼出",
object: "オブジェクト",
method: "メソッド",
parameters: "パラメータ",
result: "結果",
service: "サービス",
type: "タイプ",
content: "コンテント",
source: "ソース",
target: "ターゲット",
property: "プロパティ",

/* PreferencePane */
flowLayout: "フローレイアウト",
snapToNearestWidget: "Snap to nearest widget",
warnOnCSSOverride: "Warn on CSS Override",
liveEdit: "ライブ編集",

__dummy__: ""
});
