define(
//begin v1.x content
{
	"dateFormatItem-yM": "M.y G",
	"dateFormatItem-MMMEd": "ccc, d MMM",
	"dateFormatItem-yQQQ": "QQQ y G",
	"dateFormatItem-MMdd": "dd.MM",
	"days-standAlone-wide": [
		"–í–æ—Å–∫—Ä–µ—Å–µ–Ω—å–µ",
		"–ü–æ–Ω–µ–¥–µ–ª—å–Ω–∏–∫",
		"–í—Ç–æ—Ä–Ω–∏–∫",
		"–°—Ä–µ–¥–∞",
		"–ß–µ—Ç–≤–µ—Ä–≥",
		"–ü—è—Ç–Ω–∏—Ü–∞",
		"–°—É–±–±–æ—Ç–∞"
	],
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"–Ø",
		"–§",
		"–ú",
		"–ê",
		"–ú",
		"–ò",
		"–ò",
		"–ê",
		"–°",
		"–û",
		"–ù",
		"–î"
	],
	"dateFormatItem-yyMMMEEEd": "EEE, d MMM yy G",
	"dateFormatItem-y": "y G",
	"timeFormat-full": "H:mm:ss zzzz",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"—è–Ω–≤.",
		"—Ñ–µ–≤—Ä.",
		"–º–∞—Ä—Ç",
		"–∞–ø—Ä.",
		"–º–∞–π",
		"–∏—é–Ω—å",
		"–∏—é–ª—å",
		"–∞–≤–≥.",
		"—Å–µ–Ω—Ç.",
		"–æ–∫—Ç.",
		"–Ω–æ—è–±.",
		"–¥–µ–∫."
	],
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "LLL y G",
	"dateFormatItem-yyyyLLLL": "LLLL y G",
	"days-standAlone-narrow": [
		"–í",
		"–ü",
		"–í",
		"–°",
		"–ß",
		"–ü",
		"–°"
	],
	"dateFormatItem-yyyyMM": "MM.yyyy G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d MMMM y 'г'. G",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-yyMM": "MM.yy G",
	"dateFormat-medium": "dd.MM.yyyy G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yyMMM": "LLL yy G",
	"dateFormatItem-yMd": "d.M.y G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'г'. G",
	"months-standAlone-wide": [
		"–Ø–Ω–≤–∞—Ä—å",
		"–§–µ–≤—Ä–∞–ª—å",
		"–ú–∞—Ä—Ç",
		"–ê–ø—Ä–µ–ª—å",
		"–ú–∞–π",
		"–ò—é–Ω—å",
		"–ò—é–ª—å",
		"–ê–≤–≥—É—Å—Ç",
		"–°–µ–Ω—Ç—è–±—Ä—å",
		"–û–∫—Ç—è–±—Ä—å",
		"–ù–æ—è–±—Ä—å",
		"–î–µ–∫–∞–±—Ä—å"
	],
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q yy G",
	"timeFormat-long": "H:mm:ss z",
	"months-format-abbr": [
		"—è–Ω–≤.",
		"—Ñ–µ–≤—Ä.",
		"–º–∞—Ä—Ç–∞",
		"–∞–ø—Ä.",
		"–º–∞—è",
		"–∏—é–Ω—è",
		"–∏—é–ª—è",
		"–∞–≤–≥.",
		"—Å–µ–Ω—Ç.",
		"–æ–∫—Ç.",
		"–Ω–æ—è–±.",
		"–¥–µ–∫."
	],
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H",
	"quarters-format-abbr": [
		"1-–π –∫–≤.",
		"2-–π –∫–≤.",
		"3-–π –∫–≤.",
		"4-–π –∫–≤."
	],
	"days-format-abbr": [
		"–≤—Å",
		"–ø–Ω",
		"–≤—Ç",
		"—Å—Ä",
		"—á—Ç",
		"–ø—Ç",
		"—Å–±"
	],
	"dateFormatItem-M": "L",
	"dateFormatItem-MEd": "E, d.M",
	"days-standAlone-abbr": [
		"–í—Å",
		"–ü–Ω",
		"–í—Ç",
		"–°—Ä",
		"–ß—Ç",
		"–ü—Ç",
		"–°–±"
	],
	"dateFormat-short": "dd.MM.yy G",
	"dateFormatItem-yMMMEd": "E, d MMM y G",
	"dateFormat-full": "EEEE, d MMMM y 'г'. G",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-yMEd": "EEE, d.M.y G",
	"months-format-wide": [
		"—è–Ω–≤–∞—Ä—è",
		"—Ñ–µ–≤—Ä–∞–ª—è",
		"–º–∞—Ä—Ç–∞",
		"–∞–ø—Ä–µ–ª—è",
		"–º–∞—è",
		"–∏—é–Ω—è",
		"–∏—é–ª—è",
		"–∞–≤–≥—É—Å—Ç–∞",
		"—Å–µ–Ω—Ç—è–±—Ä—è",
		"–æ–∫—Ç—è–±—Ä—è",
		"–Ω–æ—è–±—Ä—è",
		"–¥–µ–∫–∞–±—Ä—è"
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1-–π –∫–≤–∞—Ä—Ç–∞–ª",
		"2-–π –∫–≤–∞—Ä—Ç–∞–ª",
		"3-–π –∫–≤–∞—Ä—Ç–∞–ª",
		"4-–π –∫–≤–∞—Ä—Ç–∞–ª"
	],
	"days-format-wide": [
		"–≤–æ—Å–∫—Ä–µ—Å–µ–Ω—å–µ",
		"–ø–æ–Ω–µ–¥–µ–ª—å–Ω–∏–∫",
		"–≤—Ç–æ—Ä–Ω–∏–∫",
		"—Å—Ä–µ–¥–∞",
		"—á–µ—Ç–≤–µ—Ä–≥",
		"–ø—è—Ç–Ω–∏—Ü–∞",
		"—Å—É–±–±–æ—Ç–∞"
	]
}
//end v1.x content
);