define(
//begin v1.x content
{
	"dateFormatItem-yM": "M.y",
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dateFormatItem-MMMEd": "ccc, d MMM",
	"dateFormatItem-MMdd": "dd.MM",
	"days-standAlone-wide": [
		"–í–æ—Å–∫—Ä–µ—Å–µ–Ω—å–µ",
		"–ü–æ–Ω–µ–¥–µ–ª—å–Ω–∏–∫",
		"–í—Ç–æ—Ä–Ω–∏–∫",
		"–°—Ä–µ–¥–∞",
		"–ß–µ—Ç–≤–µ—Ä–≥",
		"–ü—è—Ç–Ω–∏—Ü–∞",
		"–°—É–±–±–æ—Ç–∞"
	],
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-yyMMMEEEd": "EEE, d MMM yy G",
	"timeFormat-full": "H:mm:ss zzzz",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"–ú—É—Ö–∞—Ä—Ä–∞–º",
		"–°–∞—Ñ–∞—Ä",
		"–†–∞–±–∏-—É–ª—å-–∞–≤–≤–∞–ª—å",
		"–†–∞–±–∏-—É–ª—å-–∞—Ö–∏—Ä",
		"–î–∂—É–º–∞–¥-—É–ª—å-–∞–≤–≤–∞–ª—å",
		"–î–∂—É–º–∞–¥-—É–ª—å-–∞—Ö–∏—Ä",
		"–†–∞–¥–∂–∞–±",
		"–®–∞–∞–±–∞–Ω",
		"–†–∞–º–∞–¥–∞–Ω",
		"–®–∞–≤–≤–∞–ª—å",
		"–ó—É–ª—å-–ö–∞–∞–¥–∞",
		"–ó—É–ª—å-–•–∏–¥–∂–∂–∞"
	],
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormatItem-yyyyLLLL": "LLLL y G",
	"days-standAlone-narrow": [
		"–í",
		"–ü",
		"–í",
		"–°",
		"–ß",
		"–ü",
		"–°"
	],
	"dateFormatItem-yyyyMM": "MM.yyyy G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d MMMM y 'г'. G",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-yyMM": "MM.yy G",
	"dateFormat-medium": "dd.MM.yyyy G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yyMMM": "LLL yy G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'г'. G",
	"months-standAlone-wide": [
		"–ú—É—Ö–∞—Ä—Ä–∞–º",
		"–°–∞—Ñ–∞—Ä",
		"–†–∞–±–∏-—É–ª—å-–∞–≤–≤–∞–ª—å",
		"–†–∞–±–∏-—É–ª—å-–∞—Ö–∏—Ä",
		"–î–∂—É–º–∞–¥-—É–ª—å-–∞–≤–≤–∞–ª—å",
		"–î–∂—É–º–∞–¥-—É–ª—å-–∞—Ö–∏—Ä",
		"–†–∞–¥–∂–∞–±",
		"–®–∞–∞–±–∞–Ω",
		"–†–∞–º–∞–¥–∞–Ω",
		"–®–∞–≤–≤–∞–ª—å",
		"–ó—É–ª—å-–ö–∞–∞–¥–∞",
		"–ó—É–ª—å-–•–∏–¥–∂–∂–∞"
	],
	"dateFormatItem-yyyyMEd": "EEE, d.M.y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q yy G",
	"timeFormat-long": "H:mm:ss z",
	"months-format-abbr": [
		"–ú—É—Ö–∞—Ä—Ä–∞–º",
		"–°–∞—Ñ–∞—Ä",
		"–†–∞–±–∏-—É–ª—å-–∞–≤–≤–∞–ª—å",
		"–†–∞–±–∏-—É–ª—å-–∞—Ö–∏—Ä",
		"–î–∂—É–º–∞–¥-—É–ª—å-–∞–≤–≤–∞–ª—å",
		"–î–∂—É–º–∞–¥-—É–ª—å-–∞—Ö–∏—Ä",
		"–†–∞–¥–∂–∞–±",
		"–®–∞–∞–±–∞–Ω",
		"–†–∞–º–∞–¥–∞–Ω",
		"–®–∞–≤–≤–∞–ª—å",
		"–ó—É–ª—å-–ö–∞–∞–¥–∞",
		"–ó—É–ª—å-–•–∏–¥–∂–∂–∞"
	],
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H",
	"quarters-format-abbr": [
		"1-–π –∫–≤.",
		"2-–π –∫–≤.",
		"3-–π –∫–≤.",
		"4-–π –∫–≤."
	],
	"days-format-abbr": [
		"–≤—Å",
		"–ø–Ω",
		"–≤—Ç",
		"—Å—Ä",
		"—á—Ç",
		"–ø—Ç",
		"—Å–±"
	],
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E, d.M",
	"days-standAlone-abbr": [
		"–í—Å",
		"–ü–Ω",
		"–í—Ç",
		"–°—Ä",
		"–ß—Ç",
		"–ü—Ç",
		"–°–±"
	],
	"dateFormat-short": "dd.MM.yy G",
	"dateFormatItem-yyyyM": "M.y G",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE, d MMMM y 'г'. G",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-yMEd": "EEE, d.M.y",
	"months-format-wide": [
		"Мухаррам",
		"Сафар",
		"Раби-уль-авваль",
		"Раби-уль-ахир",
		"Джумад-уль-авваль",
		"Джумад-уль-ахир",
		"Раджаб",
		"Шаабан",
		"Рамадан",
		"Шавваль",
		"Зуль-Каада",
		"Зуль-Хиджжа"
	],
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1-–π –∫–≤–∞—Ä—Ç–∞–ª",
		"2-–π –∫–≤–∞—Ä—Ç–∞–ª",
		"3-–π –∫–≤–∞—Ä—Ç–∞–ª",
		"4-–π –∫–≤–∞—Ä—Ç–∞–ª"
	],
	"days-format-wide": [
		"–≤–æ—Å–∫—Ä–µ—Å–µ–Ω—å–µ",
		"–ø–æ–Ω–µ–¥–µ–ª—å–Ω–∏–∫",
		"–≤—Ç–æ—Ä–Ω–∏–∫",
		"—Å—Ä–µ–¥–∞",
		"—á–µ—Ç–≤–µ—Ä–≥",
		"–ø—è—Ç–Ω–∏—Ü–∞",
		"—Å—É–±–±–æ—Ç–∞"
	]
}
//end v1.x content
);