({
	"findLabel": "Find:",
	"findTooltip": "Enter text to find",
	"replaceLabel": "Replace with:",
	"replaceTooltip": "Enter text to replace with",
	"findReplace": "Find and Replace",
	"matchCase": "Match case",
	"matchCaseTooltip": "Match case",
	"backwards": "Backwards",
	"backwardsTooltip": "Search backwards for text",
	"replaceAllButton": "Replace All",
	"replaceAllButtonTooltip": "Replace all the text",
	"findButton": "Find",
	"findButtonTooltip": "Find the text",
	"replaceButton": "Replace",
	"replaceButtonTooltip": "Replace the text",
	"replaceDialogText": "Replaced ${0} occurrences.",
	"eofDialogText": "Last occurrence ${0}",
	"eofDialogTextFind": "found",
	"eofDialogTextReplace": "replaced"
})
