define(
//begin v1.x content
{
	"dateFormatItem-yM": "y/M",
	"dateFormatItem-yyyyMMMEd": "Gy年M月d日(EEE)",
	"dateFormatItem-yQ": "y/Q",
	"dayPeriods-format-wide-pm": "ÂçàÂæå",
	"dateFormatItem-GGGGyMd": "GGGGy年M月d日",
	"dateFormatItem-MMMEd": "M月d日(E)",
	"dateTimeFormat-full": "{1}{0}",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-yQQQ": "yQQQ",
	"dateFormatItem-MMdd": "MM/dd",
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "ÂçàÂâç",
	"dateFormatItem-y": "Gy年",
	"timeFormat-full": "HÊôÇmmÂàÜssÁßí zzzz",
	"dateFormatItem-yyyy": "Gy年",
	"dateFormatItem-Ed": "d日(EEE)",
	"dateFormatItem-yMMM": "yÂπ¥MÊúà",
	"days-standAlone-narrow": [
		"Êó•",
		"Êúà",
		"ÁÅ´",
		"Ê∞¥",
		"Êú®",
		"Èáë",
		"Âúü"
	],
	"dateFormatItem-yyyyMM": "Gyy/MM",
	"dateFormat-long": "Gy年M月d日",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "Gy/MM/dd",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateTimeFormat-long": "{1}{0}",
	"dateFormatItem-yyyyMd": "Gyy/M/d",
	"dateFormatItem-yyyyMMMd": "Gy年M月d日",
	"dateFormatItem-yyyyMEd": "Gyy/M/d(E)",
	"dateFormatItem-MMMd": "M月d日",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H時",
	"days-format-abbr": [
		"Êó•",
		"Êúà",
		"ÁÅ´",
		"Ê∞¥",
		"Êú®",
		"Èáë",
		"Âúü"
	],
	"dateFormatItem-M": "M月",
	"dateFormatItem-MEd": "M/d(E)",
	"dateFormatItem-hm": "ah:mm",
	"dateFormat-short": "Gy/MM/dd",
	"dateFormatItem-yMMMEd": "yÂπ¥MÊúàdÊó•(EEE)",
	"dateFormat-full": "Gy年M月d日EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yyyyQ": "Gyy/Q",
	"dateFormatItem-yMEd": "y/M/d(EEE)",
	"months-format-wide": [
		"1Êúà",
		"2Êúà",
		"3Êúà",
		"4Êúà",
		"5Êúà",
		"6Êúà",
		"7Êúà",
		"8Êúà",
		"9Êúà",
		"10Êúà",
		"11Êúà",
		"12Êúà"
	],
	"dateFormatItem-yyyyMMM": "Gy年M月",
	"dateFormatItem-d": "d日",
	"quarters-format-wide": [
		"Á¨¨1ÂõõÂçäÊúü",
		"Á¨¨2ÂõõÂçäÊúü",
		"Á¨¨3ÂõõÂçäÊúü",
		"Á¨¨4ÂõõÂçäÊúü"
	],
	"days-format-wide": [
		"Êó•ÊõúÊó•",
		"ÊúàÊõúÊó•",
		"ÁÅ´ÊõúÊó•",
		"Ê∞¥ÊõúÊó•",
		"Êú®ÊõúÊó•",
		"ÈáëÊõúÊó•",
		"ÂúüÊõúÊó•"
	],
	"dateFormatItem-h": "ah時"
}
//end v1.x content
);